name: shop_ke
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #http requests
  http: ^0.12.0+4

  #Localization and DateTimePicker
  intl: ^0.16.1

  #carousel slider
  carousel_slider: ^1.3.0
  
  #web links
  url_launcher: ^5.4.2

  #web views
  webview_flutter: ^0.3.19+9

  #state management
  provider: ^4.0.4

  #network image
  cached_network_image: ^2.0.0

  #autocomplete text field
  autocomplete_textfield: ^1.7.3

  #handling permissions
  permission_handler: ^4.4.0+hotfix.2

  #get static location
  location: ^3.0.0

  #render google maps dynamically
  google_maps_flutter: ^0.5.25+3

  #geolocation
  geolocator: ^5.3.1

  #geocoding
  geocoder: ^0.2.1

  #mpesa
  mpesa_flutter_plugin: ^0.0.5

  #### Firebase ###
  #firebase core
  firebase_core: ^0.4.5

  #firebase analytics
  firebase_analytics: ^5.0.16

  #cloud firestore
  cloud_firestore: ^0.13.7

  #firebase authentication
  firebase_auth: ^0.16.1

  #google sign in
  google_sign_in: ^4.5.1

  #rxdart
  rxdart: ^0.24.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/waiting.png
   - assets/images/hot-clearance-organic-sale.png
   - assets/images/hot-clearance-organic-sale.png
   - assets/images/50-percent-off-sale.jpg
   - assets/images/50-percent-off-sale.png
   - assets/images/back-to-school-sale.jpg
   - assets/images/empty-list.png
   - assets/images/google-logo.png
    #Dummy data
   - assets/dummy_data/dummy_inventory.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
